const { withAppBuildGradle } = require('expo/config-plugins');

// The android/ folder is generated by prebuild and gitignored, so the upload
// signing config has to be re-injected on every prebuild. Credentials come from
// Gradle properties (set them in ~/.gradle/gradle.properties or pass -P on the
// command line) — never commit them.
const SIGNING_CONFIG = `
        release {
            if (project.hasProperty('JEWELRAIN_STORE_FILE')) {
                storeFile file(JEWELRAIN_STORE_FILE)
                storePassword JEWELRAIN_STORE_PASSWORD
                keyAlias JEWELRAIN_KEY_ALIAS
                keyPassword JEWELRAIN_KEY_PASSWORD
            }
        }`;

module.exports = function withReleaseSigning(config) {
  // On EAS Build the keystore comes from EAS credentials, and EAS applies it to
  // the generated build.gradle itself. Rewriting the release signing config here
  // would fight that, so leave the stock template alone in the cloud.
  if (process.env.EAS_BUILD === 'true') {
    return config;
  }

  return withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;

    if (!gradle.includes('JEWELRAIN_STORE_FILE')) {
      gradle = gradle.replace(
        /(signingConfigs \{)/,
        `$1${SIGNING_CONFIG}`,
      );
    }

    // Point the release build type at the release config, but only when the
    // credentials are present — otherwise keep Expo's debug-signed default so
    // `assembleRelease` still works locally without the keystore.
    gradle = gradle.replace(
      /(release \{\s*\n\s*\/\/ Caution![^\n]*\n\s*\/\/ see[^\n]*\n\s*)signingConfig signingConfigs\.debug/,
      `$1signingConfig project.hasProperty('JEWELRAIN_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`,
    );

    cfg.modResults.contents = gradle;
    return cfg;
  });
};
